#!/bin/bash
set -e

# Required environment variables
# AZURE_KEY_VAULT_NAME
# TEAMBOOST_CLIENT_ID (Entra App Client ID)
# AZURE_TENANT_ID

if [ -z "$AZURE_KEY_VAULT_NAME" ] || [ -z "$TEAMBOOST_CLIENT_ID" ]; then
    echo "Error: AZURE_KEY_VAULT_NAME and TEAMBOOST_CLIENT_ID must be set."
    exit 1
fi

echo "Checking if 'entra-client-secret' exists in Key Vault: $AZURE_KEY_VAULT_NAME..."

# Check if secret exists (with error handling for RBAC propagation delay)
SECRET_EXISTS=$(az keyvault secret list --vault-name "$AZURE_KEY_VAULT_NAME" --query "[?name=='entra-client-secret'] | length(@)" -o tsv 2>&1) || {
    echo "WARNING: Cannot access Key Vault yet (RBAC permissions may still be propagating)."
    echo "Please manually add 'entra-client-secret' to Key Vault: $AZURE_KEY_VAULT_NAME"
    exit 0  # Don't fail the deployment
}

if [ "$SECRET_EXISTS" == "1" ]; then
    echo "Secret 'entra-client-secret' already exists in Key Vault. Skipping generation."
else
    echo "Secret not found. Generating new Client Secret for App: $TEAMBOOST_CLIENT_ID..."

    # Generate new secret (valid for 2 years)
    # Using specific syntax to get just the password
    NEW_SECRET=$(az ad app credential reset --id "$TEAMBOOST_CLIENT_ID" --append --display-name "TeamBoost-AutoGenerated-$(date +%Y%m%d)" --years 2 --query "password" -o tsv)

    if [ -n "$NEW_SECRET" ]; then
        echo "Successfully generated new secret."
        
        echo "Saving to Key Vault..."
        az keyvault secret set --vault-name "$AZURE_KEY_VAULT_NAME" --name "entra-client-secret" --value "$NEW_SECRET" > /dev/null
        
        echo "Secret saved to Key Vault successfully."
    else
        echo "WARNING: Failed to generate client secret (Insufficient Privileges). Please manually update 'entra-client-secret' in Key Vault or grant 'Application Administrator' role to the Service Principal."
        # Do not exit 1, just continue so deployment finishes
        exit 0
    fi
fi
